-- ANATOMY OF CREATE TABLE STATEMENT
-- ATTRIBUTE NAME ATTRIBUTE TYPE CONSTRAINT(S)
-- NAMING CONSTRAINTS "CONSTRAINT NAME"
CREATE TABLE UNIVERSITY.COURSE
(
	Crn CHAR(5) CONSTRAINT PK_COURSE_CRN PRIMARY KEY ,
	Classroom INTEGER NULL,
	Credits DECIMAL(2, 1) NOT NULL,
	PrereqCrn CHAR(5) CONSTRAINT FK_COURSE_PREREQCRN REFERENCES COURSE(Crn)
);