-- ANATOMY OF CREATE TABLE STATEMENT
-- ATTRIBUTE NAME ATTRIBUTE TYPE CONSTRAINT(S)
-- NAMING CONSTRAINTS "CONSTRAINT NAME"
CREATE TABLE UNIVERSITY.COURSE
(
	Crn CHAR(5) CONSTRAINT PK_COURSE_CRN PRIMARY KEY ,
	Classroom INTEGER CONSTRAINT DF_COURSE_CLASSROOM DEFAULT 1,
	Credits DECIMAL(2, 1) NOT NULL CHECK (Credits > 0 AND Credits <= 25),
	PrereqCrn CHAR(5) CONSTRAINT FK_COURSE_PREREQCRN REFERENCES UNIVERSITY.COURSE(Crn)
);

-- JAVA <, >, ==, !=, !, ETC...
-- SQL <>
-- DROP TABLE UNIVERSITY.COURSE;
/* */

-- INSERTING DATA
-- FLAVOR 1.
INSERT INTO UNIVERSITY.COURSE VALUES ('CS120', 362, 3, 'CS120');

-- FLAVOR 2.
INSERT INTO UNIVERSITY.COURSE (Crn, Credits) VALUES ('ATY10', 4);

-- FLAVOR 3
INSERT INTO UNIVERSITY.COURSE SELECT 'CS121', 362, 3, 'CS120';

-- SELECT STATEMENT.
/*
SELECT <ATTRIBUTE LIST>
FROM <RELATION LIST>
WHERE <SOME CONDITION> EVALUATES TO TRUE/FALSE.
*/

-- GIVE ME ALL COURSES THAT OFFER MORE THAN 1 CREDIT HOUR.
SELECT Classroom Classroom2
FROM UNIVERSITY.COURSE
UNION
SELECT Classroom Classroom2
FROM UNIVERSITY.COURSE
-- WHERE Classroom = 362;

-- DELETE (EVERYTHING)
DELETE FROM UNIVERSITY.COURSE
WHERE Crn = 'CS120';

UPDATE UNIVERSITY.COURSE
SET PrereqCrn = Crn,
Credits = Credits * 2
WHERE Crn = 'CS121'